"""Configuration."""

ANSI_RESET_SEQUENCE: str = '\033[0m'

DEFAULT_BACKGROUND_COLOUR = 49
DEFAULT_FOREGROUND_COLOUR = 39

MAX_BACKGROUND_COLOUR_LITERAL = 49
MAX_FOREGROUND_COLOUR_LITERAL = 39
MIN_BACKGROUND_COLOUR_LITERAL = 40
MIN_FOREGROUND_COLOUR_LITERAL = 30

MAX_RGB_VALUE = 255
MIN_RGB_VALUE = 0

USE_RGB_BACKGROUND = 48
USE_RGB_FOREGROUND = 38

VALID_RGB_SEQUENCE_LENGTH = 3
